### ISSUE TITLE
Incompatible with latest Werkzeug

### ISSUE THREAD

**Issue by jc-harrison** [greenape/quart-jwt-extended#3]
`tokens.py` uses `werkzeug.security.safe_str_comp`, which was removed in Werkzeug v2.1.0.

Could do with bringing this up-to-date with the latest flask-jwt-extended, I guess, where this has been fixed.

**Comment by ksaadDE** [comment]
Hi, I can provide a fix. 

**tokens.py:**
-> uncomment **from werkzeug.security import safe_str_cmp**

and uncomment **if not safe_str_cmp(data["csrf"], csrf_value)**

**instead replace it with:**
if not hmac.compare_digest(data["csrf"], csrf_value):

this applies to the safe_str_comp not found in werkzeug error. 

newest PR: #4 

Greetings from Germany!
SAAD-IT

**Comment by greenape** [comment]
Thanks @ksaadDE
